### ISSUE TITLE
1.09D Crash

### ISSUE THREAD

**Issue by XPZ2k15** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#42] opened 2021-05-27 12:07 UTC
Installed this by having plugy load the dll. I was playing Zy-El MOD (D2SE)
IN GAME RES: 1024x768

Game works perfectly fine until you kill Andariel and the cutscene happens then the game crashes. I had to disable the SGD2FreeRes.dll , reload the game, kill Andariel, go to act 2, save and exit, re-enable the SGD2FreeRes.dll so I can continue playing.

![image](https://user-images.githubusercontent.com/38363692/119822579-a95a9080-bea8-11eb-87a1-b722556c2b5d.png)

**Comment by IAmTrial** [comment] 2021-05-28 22:23
Can confirm the bug is caused by an incorrectly written ASM function. This bug had gone unnoticed because I didn't test cutscene transitions in non-GDI video modes.

https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/blob/3fff14e08cd33702282f3f9c9803ac967aca3ea5/SlashGaming-Diablo-II-Free-Resolution/src/patches/required/d2client_get_resolution_registry_patch/d2client_get_resolution_registry_patch_1_09d_shim.asm#L85-L87

In this function, the first ASM opcode is excessively dereferencing the memory location referenced by the value of the EAX register.

I will have this bug fixed in a new release. I'll also check to see if this affects other versions of the game. While waiting for the bugfix, I recommend playing on GDI (aka windowed mode) to prevent this cutscene crash from happening.

**Comment by IAmTrial** [comment] 2021-05-29 00:36
The different game version were tested and the issue will be fixed for the next release.

**Closed** 2021-05-29 00:36 UTC
Labels: bug

**Comment by IAmTrial** [comment] 2021-06-09 09:14
A new version that should fix the issue has been released in 3.0.2.1
https://github.com/mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution/releases/tag/3.0.2.1
