### ISSUE TITLE
1.14d

### ISSUE THREAD

**Issue by iamyoyz** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#37] opened 2021-05-03 11:53 UTC
First of all I would like to say thanks for putting support for 1.14d it was worth the wait... I did try installing the vanilla version of it together with pluggy 14.02 version then I set the SGD2FreeRes.dll in the pluggy config then when I tried to launch the game its still uses 640x480 and 800x600.. I'm not sure where did I go wrong

**Comment by IAmTrial** [comment] 2021-05-04 06:33
Did you edit the SGD2FreeResolution.json file that was generated after the first run?

**Comment by iamyoyz** [comment] 2021-05-04 06:36
I didnt.. I didnt know that I still have to change this one I'll just open this file using notepad?

**Comment by IAmTrial** [comment] 2021-05-04 06:40
You will need to modify the file with notepad. You can put any number of resolutions you want by modifying the `Ingame Resolutions` values, so long as it doesn't crash the game. For example:

```json
"Ingame Resolutions": [
    "640x480",
    "800x600",
    "856x480",
    "1024x600",
    "1024x768",
    "1068x600"
]
```

**Comment by iamyoyz** [comment] 2021-05-04 09:01
I will try this as soon as I get home thanks for the prompt reply

**Comment by iamyoyz** [comment] 2021-05-05 17:29
![d2](https://user-images.githubusercontent.com/74028788/117183607-5130f100-ae0a-11eb-865e-6702d0ff0de5.jpg)

I just made it by accident LOL I just use basemod to load the file and there its better now

**Comment by IAmTrial** [comment] 2021-05-06 05:45
Modifying the main menu isn't really recommended, as it doesn't actually resize the main menu images or behavior.

**Comment by iamyoyz** [comment] 2021-05-06 12:42
![bug3](https://user-images.githubusercontent.com/74028788/117299729-745fad00-aeab-11eb-89cf-9d82cd583170.jpg)
![menu](https://user-images.githubusercontent.com/74028788/117299736-7590da00-aeab-11eb-84b2-2fa52d07e649.jpg)
I notice the cinematics in the blizzard north is not full screen and what I mean in the main menu is to remove the black borders on the side :D

**Comment by IAmTrial** [comment] 2021-05-07 00:31
You could try `-nofixaspect` to see if that stretches the game window.

**Comment by iamyoyz** [comment] 2021-05-07 08:09
didnt work sorry

**Comment by IAmTrial** [comment] 2021-05-07 09:01
There are perhaps other reasons why the main menu is not stretching to the entire window. These may be dependent on the renderer configuration (e.g. Sven's Glide glide-init.exe, CnC-DDraw ddraw.ini) or the graphics card driver settings that will need to be changed to disable the preservation of the game's aspect ratio. I encourage you to try different settings on your system and enable the `-nofixaspect` at the same time.

The original problem in this issue has been resolved, and this new problem isn't exactly a problem caused by SGD2FreeRes or needs SGD2FreeRes to resolve. With that being said, I will close this issue.

**Closed by IAmTrial** 2021-05-07 09:01 UTC
