### ISSUE TITLE
Crash when changing screen resolution

### ISSUE THREAD

**Issue by Vahsify** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#138] opened 2024-07-13 14:50 UTC
Crash and error if you change several screen resolutions in a row.

**Comment by Jarcho** [comment] 2024-09-05 16:20
This is a bug in Diablo II. Changing resolutions reinitializes the sprite cache, but doesn't cancel async IO requests. If an async request attempts to use the sprite cache between when it's destroyed and recreated the game will crash.

**Comment by IAmTrial** [comment] 2024-11-21 09:39
I would also like to add onto what Jarcho mentioned. This is a vanilla bug, and likely cannot be fixed without some major changes to D2CMP. I think this bug falls out of scope of this project, since it is not directly caused by SGD2FreeRes, nor is it a goal for this project to fix such a bug.

**Closed as not planned** 2024-11-21 09:39 UTC
