### ISSUE TITLE
Panel graphics are partly off screen

### ISSUE THREAD

**Issue by cyhyraethz** [mir-diablo-ii-tools/SlashGaming-Diablo-II-Free-Resolution#62] opened 2021-08-08 04:23 UTC
The panel graphics don't line up correctly with the native UI panel, resulting in a thin black bar on top of the graphic and the gold border at the bottom of the graphic being entirely off the screen. Here's a couple cropped screenshots that highlight the problem.

About a pixel too low and partly off the screen (SGD2FreeRes):
![SGD2](https://user-images.githubusercontent.com/45051951/128620628-afdcffb1-257d-42eb-a91d-99b077a2e5d1.png)

At the right height and fully on the screen (D2HD):
![D2HD](https://user-images.githubusercontent.com/45051951/128620630-02ad9b3d-5eb8-425a-9ad8-4f66a5875607.png)

**Comment by IAmTrial** [comment] 2021-08-08 23:42
Will have it corrected.  Cause of the issue is that I based the position off of the resolution `height`, and not resolution `height - 1`.

**Comment by IAmTrial** [comment] 2021-08-12 09:09
Fixed by #68.

**Closed by IAmTrial** 2021-08-12 09:09 UTC
Labels: bug
